### ISSUE TITLE
F大源码中的make.env文件中变量名有变化

### ISSUE THREAD

**Issue by doctor-design** [mingxiaoyu/package-flippy-openwrt#6]
F大源码中的make.env文件中关于wifi设置的变量名有变化，不知道大佬脚本更新没有，至少我看到1.0版是没更新，
否则会导致编译(刷入emmc)后wifi找不到等问题。不知道f大那些判断如何加进去，还是直接定死。

**Comment by mingxiaoyu** [comment]
done.
