### ISSUE TITLE
不能打包了

### ISSUE THREAD

**Issue by doctor-design** [mingxiaoyu/package-flippy-openwrt#8]
f大打包文件夹结构有变化，现在已不能打包了。希望大佬能更新脚本。

**Comment by mingxiaoyu** [comment]
修好了。。。
githubrepository 这个参数可以指定 你自己的内核 git 的地址  例如你自己的名字 doctor-design

**Comment by mingxiaoyu** [comment]
shell 版 没空修，不想修了。近来真的很忙
